version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
        
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matrika
      MYSQL_USER: matrika
      MYSQL_PASSWORD: matrika
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    restart: always
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - ENV=development
      - MONGO_URL=mongodb://mongo:27017/matrika
      - DB_URL=mysql://matrika:matrika@mysql:3306/matrika
      - PORT=3003
      - LOG_FILE=/var/log/matrika.log
      - LOG_LEVEL=debug
      - SECRET=trumpisgay
      - ADMIN_PASSWORD=admin
      - ADMIN_USERNAME=admin
 
    depends_on:
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:3003/api/v1
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  migrate:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/matrika
      - DB_URL=mysql://matrika:matrika@mysql:3306/matrika
    depends_on:
      mysql:
        condition: service_healthy
    restart: no
    command: >
      sh -c "npm run migrate && npm run seed"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules


volumes:
  mongo-data:
