version: "3.7"

services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: .\backend
      dockerfile: Dockerfile
    image: matrika-back
    container_name: matrika-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www/backend
    networks:
      - matrika

  db:
    image: mysql:8.0
    container_name: matrika-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - matrika-datavolume:/var/lib/mysql
    networks:
      - matrika

  nginx:
    image: nginx:alpine
    container_name: matrika-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./frontend/dist:/var/www/frontend/dist
      - ./backend:/var/www/backend
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - matrika

networks:
  matrika:
    driver: bridge


volumes:
  matrika-datavolume: